# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeesDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('employment_type', models.CharField(blank=True, choices=[(b'PE', b'permanent'), (b'PB', b'probationary'), (b'IN', b'intern'), (b'CT', b'contract')], max_length=20, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to=hr.models.upoad_location)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.EmployeesDirectory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['firstname', 'lastname'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.EmployeesDirectory')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveAccurals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveType', models.CharField(choices=[(b'CL', b'casual'), (b'PL', b'privilege'), (b'SL', b'sick'), (b'WFH', b'workfromhome'), (b'COMP', b'compensation'), (b'LOP', b'lossofpay')], default=b'PL', max_length=25)),
                ('accuredLeaves', models.IntegerField(default=12)),
                ('last_update_timestamp', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.EmployeesDirectory')),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveType', models.CharField(choices=[(b'CL', b'casual'), (b'PL', b'privilege'), (b'SL', b'sick'), (b'WFH', b'workfromhome'), (b'COMP', b'compensation'), (b'LOP', b'lossofpay')], default=b'PL', max_length=25)),
                ('startedDate', models.DateField()),
                ('endDate', models.DateField()),
                ('numberOfDays', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[(b'CREATED', b'created'), (b'SUBMITTED', b'submitted'), (b'APPROVED', b'approved'), (b'REJECTED', b'rejected'), (b'CLOSED', b'closed'), (b'REOPENED', b'reopened')], default=b'CREATED', max_length=25)),
                ('reason', models.TextField(max_length=508)),
                ('currentProject', models.CharField(max_length=254)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_update_timestamp', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.EmployeesDirectory')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.EmployeesDirectory'),
        ),
    ]
