# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('country_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeesDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('employment_type', models.CharField(blank=True, choices=[(b'PE', b'Permanent'), (b'PB', b'Probationary'), (b'IN', b'Intern'), (b'CT', b'Contract')], default=b'PE', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('designation', models.CharField(max_length=100)),
                ('is_manager', models.BooleanField(default=False)),
                ('image', models.FileField(blank=True, null=True, upload_to=hr.models.upoad_location)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.EmployeesDirectory')),
            ],
            options={
                'ordering': ['firstname', 'lastname'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.EmployeesDirectory')),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=254)),
                ('date', models.DateField()),
                ('year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], default=2016)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Country')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveAccurals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveType', models.CharField(choices=[(b'CL', b'Casual'), (b'PL', b'Privilege'), (b'SL', b'Sick'), (b'WFH', b'Work From Home'), (b'COMP', b'Compensation'), (b'LOP', b'Loss Of Pay')], default=b'PL', max_length=25)),
                ('accuredLeaves', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('last_update_timestamp', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.EmployeesDirectory')),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveType', models.CharField(choices=[(b'CL', b'Casual'), (b'PL', b'Privilege'), (b'SL', b'Sick'), (b'WFH', b'Work From Home'), (b'COMP', b'Compensation'), (b'LOP', b'Loss Of Pay')], default=b'PL', max_length=25)),
                ('startedDate', models.DateField()),
                ('endDate', models.DateField()),
                ('numberOfDays', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('status', models.CharField(choices=[(b'CREATED', b'Create'), (b'SUBMITTED', b'Submit'), (b'APPROVED', b'Approve'), (b'REJECTED', b'Reject'), (b'CLOSED', b'Close'), (b'REOPENED', b'Re-open'), (b'DISCARD', b'Discard')], default=b'CREATED', max_length=25)),
                ('reason', models.CharField(max_length=254)),
                ('rejection_reason', models.TextField(max_length=300)),
                ('currentProject', models.CharField(max_length=254)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_update_timestamp', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.EmployeesDirectory')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('is_headoffice', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Country')),
            ],
        ),
        migrations.AddField(
            model_name='employeesdirectory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Organization'),
        ),
        migrations.AddField(
            model_name='employeesdirectory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.EmployeesDirectory'),
        ),
    ]
